---
- name: Deploy Dockerized Application to EC2
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: asi-insurance-app
        tag: "{{ lookup('env', 'BUILD_NUMBER') }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: asi-insurance-container
        image: asi-insurance-app:{{ lookup('env', 'BUILD_NUMBER') }}
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "80:80"  # Adjust as needed for your application
