---
- name: Deploy ASI Insurance Application
  hosts: webserver
  become: yes
  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull the application image from Docker Hub
      docker_image:
        name: asi-insurance-app:latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: asi-insurance-container
        image: asi-insurance-app:latest
        state: started
        ports:
          - "80:3000"
